spring.application.name=dia-1
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.url=jdbc:mysql://localhost:3306/local
#jdbc:mysql://localhost:3306/?user=SYSTEM
#spring.datasource.url=jdbc:mysql://local.cbgcymqmcnog.ap-south-1.rds.amazonaws.com:3306/local?serverTimezone=Asia/Kolkata
#spring.datasource.url=jdbc:mysql://google/local?cloudSqlInstance=turing-thought-441917-i8:us-central1:system&socketFactory=com.google.cloud.sql.mysql.SocketFactory
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=new_password
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.main.allow-circular-references=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB
server.tomcat.max-http-form-post-size=100MB
server.tomcat.max-swallow-size=100MB
#logging.level.org.springframework.security=DEBUG
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
server.address=0.0.0.0
server.port=8080

###############################################################################################
spring.web.resources.static-locations=classpath:/static/,file:C:/Users/Admin/Downloads/uploads/
app.server.host=192.168.1.6
app.server.port=8080
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379
management.endpoints.web.exposure.include=*
app.base-url=http://192.168.1.50:8080
#app.base-url=https://sports-sheriff-regions-aluminum.trycloudflare.com
app.qr-dir=C:/Users/Admin/Downloads/uploads/qr_codes/
app.qr-public-path=/uploads/qr_codes/
app.uploads.path=file:C:/Users/Admin/Downloads/uploads/
save.uploads.path=C:/Users/Admin/Downloads/uploads/
delete.baseUploadDir.path=C:/Users/Admin/Downloads
################################################################################

#spring.web.resources.static-locations=classpath:/static/,file:C:/Users/Hirenn/Desktop/Newfolder(3)/setup/setup/uploads/
#app.server.host=192.168.1.6
#app.server.port=8080
#spring.cache.type=redis
#spring.redis.host=localhost
#spring.redis.port=6379
#management.endpoints.web.exposure.include=*
#app.base-url=http://192.168.1.50:8080
##app.base-url=https://sports-sheriff-regions-aluminum.trycloudflare.com
#app.qr-dir=C:/Users/Hirenn/Desktop/Newfolder(3)/setup/setup/uploads/qr_codes/
#app.qr-public-path=/uploads/qr_codes/
#app.uploads.path=file:C:/Users/Hirenn/Desktop/Newfolder(3)/setup/setup/uploads/
#save.uploads.path=C:/Users/Hirenn/Desktop/Newfolder(3)/setup/setup/uploads/
#delete.baseUploadDir.path=C:/Users/Hirenn/Desktop/Newfolder(3)/setup/setup